version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres!
      - POSTGRES_PASSWORD=postgres!
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/product
      - SPRING_DATASOURCE_USERNAME=postgres!
      - SPRING_DATASOURCE_PASSWORD=postgres!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres!
      - POSTGRES_PASSWORD=postgres!
      - POSTGRES_DB=product
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"