server:
  port:
    - 80:80
spring:
  datasource:
    password: postgres!
    url: jdbc:postgresql://localhost:5432/product
    username: postgres!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect